# Adapted from https://github.com/XigenIO/Docker-ArchMirror
name: arch-mirror

services:
  arch-mirror:
    container_name: arch-mirror
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../volumes/arch-mirror:/data
    # If tty, it always rsyncs
    # Else, it checks lastupdate
    # tty: true
    environment:
      # Changable to any Tier 1 mirror (https://www.archlinux.org/mirrors/)
      source_url: rsync://losangeles.mirror.pkgbuild.com/packages/
      lastupdate_url: https://losangeles.mirror.pkgbuild.com/lastupdate
      tls: "1"
