# Public, anonymous, read-only Arch Linux mirror.
pid file = /run/rsyncd.pid
lock file = /run/rsyncd.lock
log file = /dev/stdout
max connections = 25
timeout = 600

[packages]
    path = /data
    comment = Arch Linux package mirror
    read only = yes
    list = yes
    use chroot = yes
    uid = nobody
    gid = nobody
